### ISSUE TITLE
Issue is still reported after applying the quick fix

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/salesforcedx-vscode-slds#143]
The following CSS:

```css
foo {
    color: rgb(221, 219, 218);
}
```

results in the recommendation from the SLDS Validator:

`Consider replacing "rgb(221, 219, 218)" with an updated design token: "colorGray5": SLDS (DESIGN_TOKEN)` 

with quick fix:

`Update token to 'colorGray5'`

Applying that quick fix, the code is changed to:

```css
foo {
    color: var(--lwc-colorGray5, rgb(221, 219, 218));
}
```

but the exact same recommendation and fix are again reported, and applying the fix again results in:

```css
foo {
    color: var(--lwc-colorGray5, var(--lwc-colorGray5, rgb(221, 219, 218)));
}
```

This happens ad nauseum, so the only option is to accept the fix (if desired) and then suppress the reported issue via `sldsValidatorIgnore` or `sldsValidatorIgnoreNextLine`.

Let me know if that doesn't provide enough information to reproduce the described behavior.
